export const aboutSkillsData = {
  frontend: [
    "Next.js",
    "React",
    "TypeScript",
    "Tailwind CSS",
    "Material-UI",
  ],
  backend: [
    "Node.js",
    "Express.js",
    "REST APIs",
    "JWT Auth",
  ],
  database: [
    "PostgreSQL",
    "Prisma",
    "MongoDB",
    "Supabase",
  ],
  tools: [
    "Git",
    "Vercel",
    "Stripe",
    "OpenAI API",
    "Postman",
    "npm/yarn",
  ],
  other: [
    "Authentication",
    "Payments",
    "File Uploads",
    "Email Templates",
    "Drag & Drop (DnD Kit)",
  ],
  competitive: [
    "C++17/20",
    "STL",
    "Algorithms",
    "Data Structures",
    "Dynamic Programming",
    "Graphs",
    "Greedy",
    "Number Theory",
    "Codeforces",
    "LeetCode",
    "AtCoder",
  ],
} as const;
